server {
    listen 8080;
    listen [::]:8080;

    # Atur Document Root ke folder public Laravel
    root /home/site/wwwroot/public;

    # Tambahkan index.php sebagai file index utama
    index index.php;

    # Atur server name (opsional, bisa dibiarkan default)
    server_name _;
    port_in_redirect off;

    location / {
        # Coba layani file secara langsung, lalu direktori, jika tidak ada, fallback ke index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Lokasi untuk memproses file PHP
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_intercept_errors on;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 3600;
        fastcgi_read_timeout 3600;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
    }

    # Larang akses ke file .ht
    location ~ /\.ht {
        deny all;
    }

    # Larang akses ke direktori .git
    location ~ /\.git {
        deny all;
    }
}
